Inventario.MVC/Controllers/CategoriasController.cs
using Inventario.MVC.Data;
using Inventario.MVC.DTOs;
using Inventario.MVC.Filters;
using Inventario.MVC.Interfaces;
using Inventario.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inventario.MVC.Controllers;

public class CategoriasController : Controller {
    private readonly ApplicationDbContext _context;
    private readonly ICategoriaRepository _categoriaRepository;
    private readonly ICategoriaMapper _categoriaMapper;

    public CategoriasController(ICategoriaRepository categoriaRepository, ICategoriaMapper categoriaMapper, ApplicationDbContext context)
    {
        _categoriaRepository = categoriaRepository;
        _categoriaMapper = categoriaMapper;
        _context = context;
    }

    public IActionResult Index() {
      return View();
    }

    public async Task<IActionResult> GetCategorias(){
      var categorias = await _categoriaRepository.GetCategories();
      var categoriasDTO = _categoriaMapper.Map(categorias);

      return Ok(new ApiResponse<IEnumerable<CategoriaDTO>> {
        Data = categoriasDTO,
        Message = "Listado de categorias obtenido correctamente",
        Success = true
      });
    }
    
    public async Task<IActionResult> GetCategoriaById(int id){
      Categoria? categoria = await _categoriaRepository.GetCategoryById(id);
      
      if (categoria is null){
        return NotFound(new ApiResponse<CategoriaDTO?> {
          Data = null,
          Message = "No se encontro ninguna categoria",
          Success = false
        });
      }

      var categoriaDTO = _categoriaMapper.Map(categoria);

      return Ok(new ApiResponse<CategoriaDTO> {
        Data = categoriaDTO,
        Message = "Categoria obtenida correctamente",
        Success = true
      });
    }

    [ServiceFilter(typeof(FiltroValidacionModelos))]
    public async Task<IActionResult> CreateCategoria(CategoriaCreateDTO categoriaCreateDTO) {
      bool alreadyExist = await _categoriaRepository.ExistCategoryByName(categoriaCreateDTO.Nombre);

      if (alreadyExist){
        return Conflict(new ApiResponse<object?>{
          Message = $"Ya existe una categoria con el nombre {categoriaCreateDTO.Nombre}",
          Success = false
        });
      }

      Categoria categoria = _categoriaMapper.Map(categoriaCreateDTO);
      bool categoriaIsSaved = await _categoriaRepository.CreateCategory(categoria);

      if (!categoriaIsSaved) {
        return StatusCode(
          StatusCodes.Status500InternalServerError,
          new ApiResponse<object?> { 
            Data = null,
            Message = "Algo salio mal, no se pudo crear la categoria",
            Success = false
          }
        );
      }

      return Ok(new ApiResponse<bool> {
        Data = true,
        Message = "Categoria creada correctamente",
        Success = true
      });
    }

    // [ServiceFilter(typeof(FiltroValidacionModelos))]
    public async Task<IActionResult> EditCategoria(int id, CategoriaUpdateDTO categoriaUpdateDTO) {

      bool alreadyExist = await _categoriaRepository.ExistCategoryByName(categoriaUpdateDTO.Nombre, id);

      if (alreadyExist){
        return Conflict(new ApiResponse<object?>{
          Message = $"Ya existe una categoria con el nombre {categoriaUpdateDTO.Nombre}",
          Success = false
        });
      }

      Categoria? categoriaFound = await _categoriaRepository.GetCategoryById(id);

      if (categoriaFound is null){
        return NotFound(new ApiResponse<Categoria?>() { 
          Success = false,
          Message = "Categoria no encontrada",
        });
      }

      _categoriaMapper.Map(categoriaFound, categoriaUpdateDTO);
      
      // Para que llegue la exception, en este caso categoria esta vacio
      _context.Categorias.Update(categoriaFound);
      await _context.SaveChangesAsync();

      // bool saved = await _categoriaRepository.UpdateCategory(categoriaFound);
      // if (!saved) {
      //   return BadRequest(new ApiResponse<CategoriaDTO?>() { 
      //     Success = false,
      //     Message = "No se pudo editar la categoria",
      //   });
      // }

      return Ok(new ApiResponse<CategoriaDTO?>() { 
        Success = true,
        Message = "Categoria actualizada exitosamente",
        Data = null
      });
    }

    public async Task<IActionResult> DeleteCategoria ([FromRoute] int id) {
      Categoria? categoria = await _categoriaRepository.GetCategoryById(id);

      if (categoria is null){
        return NotFound(new ApiResponse<object?>() { 
          Success = false,
          Message = "No se encontro la categoria a deshabilitar",
        });
      }

      bool existInProducto = await _categoriaRepository.ExistCategoriaInProducto(categoria.Id);
      if (existInProducto){
        return Conflict(new ApiResponse<object?>(){
          Success = false,
          Message = "La categoria existe en un producto, elimine primero este",
        });
      }

      bool result = await _categoriaRepository.ToggleCategoryAvailability(categoria, !categoria.Eliminado);

      if (!result){
        return BadRequest(new ApiResponse<object?>() { 
          Success = false,
          Message = "Algo salio mal, no se pudo eliminar la categoria",
        });
      }

      return NoContent();
    }
}

Inventario.MVC/Controllers/MovimientosController.cs
using Inventario.MVC.DTOs;
using Inventario.MVC.Filters;
using Inventario.MVC.Interfaces;
using Inventario.MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Inventario.MVC.Controllers;

public class MovimientosController : Controller
{
    private readonly IMovimientoRepository _movimientoRepository;
    private readonly IMovimientoMapper _movimientoMapper;

    public MovimientosController(IMovimientoRepository movimientoRepository, IMovimientoMapper movimientoMapper)
    {
        _movimientoRepository = movimientoRepository;
        _movimientoMapper = movimientoMapper;
    }

    public IActionResult Index(){
    
      return View();
    }

    [ServiceFilter(typeof(FiltroValidacionModelos))]
    public async Task<IActionResult> NuevoMovimiento (MovimientoCreateDTO movimientoCreateDTO) {
      var movimiento = _movimientoMapper.Map(movimientoCreateDTO);
      Movimiento? movimientoSaved = await _movimientoRepository.NewMovimiento(movimiento);

      if (movimientoSaved is null) {
        return BadRequest(new ApiResponse<object?>{ 
          Success = false,
          Message = "Algo salio mal, no se pudo crear el movimiento",
          Data = null
        });
      }

      MovimientoDTO movimientoSavedDTO = _movimientoMapper.Map(movimientoSaved);

      return Ok(new ApiResponse<MovimientoDTO>{ 
        Success = true,
        Message = "Movimiento realizado exitosamente",
        Data = movimientoSavedDTO
      });
    }

    public async Task<IActionResult> GetMovimientos (){
      var movimientos = await _movimientoRepository.GetMovimientos();
      var movimientoDTOs =  _movimientoMapper.Map(movimientos);

      return Ok(new ApiResponse<List<MovimientoDTO>> {
        Success = true,
        Message = "Listado de movimientos",
        Data = movimientoDTOs
      });
    }
}

Inventario.MVC/Controllers/ProductosController.cs
using Inventario.MVC.Data;
using Inventario.MVC.DTOs;
using Inventario.MVC.Filters;
using Inventario.MVC.Interfaces;
using Inventario.MVC.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Inventario.MVC.Controllers;

public class ProductosController : Controller
{
  private readonly IProductoMapper _productoMapper;
  private readonly IProductoRepository _productoRepo;

  // private readonly ICategoriaMapper _categoriaMapper; 
  private readonly ICategoriaRepository _categoriaRepo;

  public ProductosController(IProductoRepository productoRepo, IProductoMapper productoMapper, ICategoriaRepository categoriaRepo)
  {
    _productoMapper = productoMapper;
    _productoRepo = productoRepo;

    // _categoriaMapper = categoriaMapper;
    _categoriaRepo = categoriaRepo;
  }

  public async Task<IActionResult> Index() {
    var categorias = await _categoriaRepo.GetCategories();

    categorias = categorias
      .Append(new Categoria { Id = 0, Nombre = "[SELECCIONE UNA CATEGORIA]" })
      .OrderBy(c=> c.Id)
      .ToList();

    ViewBag.Categorias = new SelectList(categorias, "Id", "Nombre");

    // List<SelectListItem> tiposSelectItems = new () {
    //   new ("[SELECCIONE UN TIPO DE MOVIENTO]", "-1")
    // };
  
    // var tipoMovimientos = Enum.GetValues(typeof(TipoMovimiento)).Cast<TipoMovimiento>();

    // tiposSelectItems.AddRange(
    //   tipoMovimientos.Select(t=> new SelectListItem {
    //     Value = t.GetHashCode().ToString(),
    //     Text = t.ToString()
    //   })
    // );

    // ViewBag.TiposMovimientos = tiposSelectItems.OrderBy(t=> t.Value).ToList();

    // var productos = await _productoRepo.GetProducts();
    // productos = productos
    //   .Append(new Producto { Id = 0, Nombre = "[SELECCIONE UN PRODUCTO]" })
    //   .OrderBy(p=> p.Id)
    //   .ToList();

    // ViewBag.Productos = new SelectList(productos, "Id", "Nombre");

    return View();
  }

  public async Task<IActionResult> GetProducts (){
    var productos = await _productoRepo.GetProducts();
    var productosDTO = _productoMapper.Map(productos);

    return Ok(new ApiResponse<IEnumerable<ProductoDTO>> (){
      Success = true,
      Message = "Productos obtenidos correctamente",
      Data = productosDTO
    });
  }

  public async Task<IActionResult> GetProductById (int id){
    var producto = await _productoRepo.GetProductById(id);

    if (producto is null){
      return NotFound(new ApiResponse<ProductoDTO?> (){
        Success = false,
        Message = "No se pudo recuperar el producto",
      });
    }

    var productosDTO = _productoMapper.Map(producto);

    return Ok(new ApiResponse<ProductoDTO> (){
      Success = true,
      Message = "Producto obtenido correctamente",
      Data = productosDTO
    });
  }

  [ServiceFilter(typeof(FiltroValidacionModelos))]
  public async Task<IActionResult> CreateProduct(ProductoCreateDTO productoCreateDTO)
  {
    bool alreadyExist = await _productoRepo.ExistProductByBarcode(productoCreateDTO.CodigoBarra);

    if (alreadyExist){
      return Conflict(new ApiResponse<object?> {
        Success = false,
        Message = "Ya existe un producto con el código de barra",
        Data = null
      });
    }

    var producto = _productoMapper.Map(productoCreateDTO);
    Producto? productoSaved = await _productoRepo.CreateProduct(producto);

    if (productoSaved is null) {
      return BadRequest(new ApiResponse<object?>{ 
        Success = false,
        Message = "Algo salio mal, no se pudo crear el producto",
        Data = null
      });
    }

    ProductoDTO productoSavedDTO = _productoMapper.Map(productoSaved);

    return Ok(new ApiResponse<ProductoDTO>{ 
      Success = true,
      Message = "Producto creado exitosamente",
      Data = productoSavedDTO
    });
  }

  [ServiceFilter(typeof(FiltroValidacionModelos))]
  public async Task<IActionResult> EditProduct([FromRoute] int id, ProductoUpdateDTO productoUpdateDTO)
  {
    bool alreadyExist = await _productoRepo.ExistProductByBarcode(productoUpdateDTO.CodigoBarra, id);

    if (alreadyExist){
      return Conflict(new ApiResponse<ProductoDTO?>() { 
        Success = false,
        Message = "Ya existe un producto con el codigo de barra",
      });
    }

    Producto? productFound = await _productoRepo.GetProductById(id);

    if (productFound is null){
      return NotFound(new ApiResponse<Producto?>() { 
        Success = false,
        Message = "El producto a editar no existe",
      });
    }

    _productoMapper.Map(productFound, productoUpdateDTO);
    bool saved = await _productoRepo.UpdateProduct(productFound);
  
    if (!saved) {
      return BadRequest(new ApiResponse<ProductoDTO?>() { 
        Success = false,
        Message = "No se pudo editar el producto",
      });
    }

    // ProductoDTO newProductoDTO = _productoMapper.Map(productFound);
    
    return Ok(new ApiResponse<ProductoDTO?>() { 
      Success = true,
      Message = "Producto actualizado exitosamente",
      Data = null
    });
  }

  public async Task<IActionResult> DeleteProduct ([FromRoute] int id) {
    Producto? product = await _productoRepo.GetProductById(id);

    if (product is null){
      return NotFound(new ApiResponse<object?>() { 
        Success = false,
        Message = "El producto a eliminar no existe",
      });
    }

    bool existInMovimientos = await _productoRepo.ExistProductInMovimiento(product.Id);
    if (existInMovimientos){
      return Conflict(new ApiResponse<object?>(){
        Success = false,
        Message = "El producto existe en un movimiento, elimine primero este",
      });
    }

    bool result = await _productoRepo.ToggleProductAvailability(product, !product.Eliminado);

    if (!result){
      return BadRequest(new ApiResponse<object?>() { 
        Success = false,
        Message = "Algo salio mal, no se pudo eliminar el producto",
      });
    }

    return NoContent();
  }
}

Inventario.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventario.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inventario.MVC.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.min.css">

    <link rel='stylesheet' href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                   <i class='bx bx-package'></i> 
                    Inventario
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movimientos" asp-action="Index">Movimientos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Inventario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/utilidades.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.5/dist/sweetalert2.all.min.js"></script> 

    @* <script type="module" src="https://unpkg.com/@@fluentui/web-components"></script> *@

</body>
</html>